In [1]:
import torch
import numpy

In [2]:
x = torch.arange(6).reshape(3,2)

In [3]:
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [5]:
type(x[1,1])

torch.Tensor

In [6]:
x[:,1] # all value of column #1 horizontal #index

tensor([1, 3, 5])

In [7]:
x[:,1:] # all value of column #1 vertically # slicing

tensor([[1],
        [3],
        [5]])

In [10]:
x = torch.arange(10)

In [11]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [12]:
x.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [15]:
x = x.reshape(2,5)

In [16]:
x =  torch.arange(10)

In [17]:
x.shape

torch.Size([10])

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [19]:
z = x.view(2,5)

In [20]:
z

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [21]:
x[0] = 9999

In [22]:
x

tensor([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [23]:
z

tensor([[9999,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [34]:
x = torch.arange(10)

In [35]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
x.shape

torch.Size([10])

In [37]:
# INFER what the 2nd dimension 
x.view(2,-1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [44]:
a = torch.tensor([1.,2.,3.])

In [67]:
b= torch.tensor([4.,5.,6.])


In [41]:
a

tensor([1, 2, 3])

In [45]:
a.dtype

torch.float32

In [42]:
b

tensor([4, 5, 6])

In [46]:
a+b

tensor([5., 7., 9.])

In [47]:
torch.add(a,b)

tensor([5., 7., 9.])

In [56]:
# The add method performs element-wise addition between two tensors and returns a new tensor containing the result.
# It does not modify the original tensor and instead creates a new tensor to store the result of the addition.


# The add_ method also performs element-wise addition between two tensors, 
# but it modifies the original tensor in place, updating its values with the result of the addition.
# The syntax for using add_ is as follows:

a.mul(b) #a = a * b


tensor([ 16.,  50., 108.])

In [60]:
a = torch.tensor([1.,2.,3.])

In [61]:
b

tensor([4, 5, 6])

In [62]:
a*b

tensor([ 4., 10., 18.])

In [65]:
a.dtype

torch.float32

In [68]:
b.dtype

torch.float32

In [63]:
a.mul(b)

tensor([ 4., 10., 18.])

In [69]:
a.dot(b)

tensor(32.)

In [71]:
a = torch.tensor([[0,2,4],[1,3,5]])

In [72]:
a

tensor([[0, 2, 4],
        [1, 3, 5]])

In [73]:
b = torch.tensor([[6,7],[8,9],[10,11]])

In [74]:
b

tensor([[ 6,  7],
        [ 8,  9],
        [10, 11]])

In [75]:
a.shape

torch.Size([2, 3])

In [76]:
b.shape

torch.Size([3, 2])

In [77]:
torch.mm(a,b)

tensor([[56, 62],
        [80, 89]])

In [78]:
a @ b

tensor([[56, 62],
        [80, 89]])

In [79]:
x = torch.tensor([2.,3.,4.,5,])

In [80]:
x.norm()

tensor(7.3485)

In [81]:
x.numel()

4

In [82]:
len(x)

4

In [83]:
len(a)

2

In [84]:
a.numel()

6