In [1]:
import torch

In [2]:
import numpy as np

In [3]:
torch.__version__

'2.0.1'

In [4]:
arr = np.array ([1,2,3,4,5])

In [5]:
print(arr)

[1 2 3 4 5]


In [6]:
arr.dtype

dtype('int32')

In [7]:
type(arr)

numpy.ndarray

In [8]:
x = torch.from_numpy(arr)

In [9]:
type(x)

torch.Tensor

In [10]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [11]:
x

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [12]:
x.dtype

torch.int32

In [13]:
arr2d = np.arange(0.0,12.0)

In [14]:
arr2d

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [15]:
arr2d = arr2d.reshape(4,3)

In [16]:
x2 = torch.from_numpy(arr2d)

In [17]:
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [18]:
arr

array([1, 2, 3, 4, 5])

In [19]:
x

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [20]:
arr[0] = 99

In [21]:
arr

array([99,  2,  3,  4,  5])

In [22]:
x

tensor([99,  2,  3,  4,  5], dtype=torch.int32)

In [23]:
my_arr = np.arange(0,10)

In [24]:
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
my_tensor = torch.tensor(my_arr)

In [26]:
my_other_tensor = torch.from_numpy(my_arr)

In [27]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [28]:
my_other_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [29]:
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
my_other_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [31]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [32]:
new_arr = np.array([1,2,3])

In [33]:
new_arr.dtype

dtype('int32')

In [34]:
torch.tensor(new_arr)

tensor([1, 2, 3], dtype=torch.int32)

In [35]:
my_tensor = torch.Tensor(new_arr)

In [36]:
my_tensor.dtype

torch.float32

In [37]:
torch.empty(4,2)

tensor([[7.0065e-44, 8.1275e-44],
        [6.7262e-44, 6.8664e-44],
        [8.1275e-44, 7.1466e-44],
        [7.9874e-44, 6.4460e-44]])

In [38]:
torch.zeros(4,3,dtype = torch.int64)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [39]:
torch.ones(4,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [40]:
torch.arange(0,18,2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [41]:
torch.linspace(0,18,12).reshape(3,4)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])

In [42]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [43]:
my_tensor = torch.tensor([1,2,3])

In [44]:
my_tensor.dtype

torch.int64

In [45]:
my_tensor =my_tensor.type(torch.int32)

In [46]:
my_tensor.dtype

torch.int32

In [47]:
torch.rand(4,3)

tensor([[0.0411, 0.9328, 0.8836],
        [0.9187, 0.7515, 0.0620],
        [0.2578, 0.0210, 0.7947],
        [0.0477, 0.3022, 0.8534]])

In [48]:
torch.randn(4,3)

tensor([[-0.8009, -0.0494,  1.4476],
        [-0.4067, -2.3506, -0.2768],
        [ 0.3152,  2.1003,  0.4038],
        [ 0.8338, -0.9867, -0.4344]])

In [49]:
torch.randint(low = 0, high = 11, size = (5,5))

tensor([[ 1,  6, 10,  8,  3],
        [ 9,  3,  9,  6,  3],
        [ 3,  8,  8,  2,  3],
        [ 0,  5,  5,  9,  4],
        [ 6,  4, 10,  9,  9]])

In [50]:
x = torch.zeros(2,5)

In [51]:
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [52]:
x.shape

torch.Size([2, 5])

In [53]:
torch.rand_like(x)

tensor([[0.5636, 0.5086, 0.9721, 0.9173, 0.5140],
        [0.5123, 0.3473, 0.6402, 0.4683, 0.7217]])

In [54]:
torch.randn_like(x)

tensor([[-0.2445,  1.3150,  0.1541,  0.9214,  1.3340],
        [-0.5576, -0.7623,  0.8238,  0.6229, -0.6241]])

In [55]:
torch.randint_like(x, low = 0, high = 11)

tensor([[1., 4., 1., 5., 7.],
        [9., 2., 1., 2., 0.]])

In [56]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [57]:
torch.rand(2,3)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])